### ISSUE TITLE
Nothing happens after importing an image into the eCraft Idea tool

### ISSUE THREAD

**Issue by ToonTalk** [ecraft2learn/uui#10]

**Comment by afsheenam** [comment]
As Tapani did a demo on this, after loading the image, the user should "draw a box", in which the image will show as a texture. Therefore there is no bug here, but I think a short balloon help will not be a bad idea.

**Comment by ToonTalk** [comment]
Or the image appears together with handles for resizing and moving it.

**Comment by ToonTalk** [comment]
Instead of closing I would have changed this from bug to enhancement. This is a very confusing interface.
