### ISSUE TITLE
Search tool returns no results for "robot"

### ISSUE THREAD

**Issue by ToonTalk** [ecraft2learn/uui#12]
The console has 100s of copies of:

www-widgetapi.js:94 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://ecraft2learn.github.io').

**Comment by ToonTalk** [comment]
After a very long wait (though on a slow Internet connection) a list of youtube videos appeared.

The first in the list (https://www.youtube.com/watch?v=inl6ivGvzSk) is a really TERRIBLE video even though it is very popular (among babies).  Here is a detailed story about these videos: https://medium.com/@jamesbridle/something-is-wrong-on-the-internet-c39c471271d2

The second said in the title it was for kindergarten children.

Perhaps while the search is still ongoing but no results have been found the interface says "please wait" or the cursor turns into a spinning wait icon.

**Comment by Calkin-eC2L** [comment]
This is exactly the type of issues that we need to avoid. The internet (particularly youtube) is a very weird place, we don't want to bring its weirdness to school grounds with our tools...
I would say to limit the search to community of practices databases (e.g., instructables, tinkercad, etc.=

**Comment by ToonTalk** [comment]
I agree about removing YouTube. I haven't seen similar problems with the Flickr photos. Probably should keep it but maybe only after more testing.
