### ISSUE TITLE
Snap4Ard not connecting to Ard board through the UUI

### ISSUE THREAD

**Issue by Calkin-eC2L** [ecraft2learn/uui#14]
I have been trying to make this work on my laptop but it has not been possible for me to connect the Ard board to the programming environment through the UUI. Notice that I can connect just fine through the snap4arduino.rocks/run/ url. However, I can not use the AI blocks through this site. Basically, on one side I could use the AI blocks within the UUI but not connect to the ard board or I could connect to the ard board but not use the AI blocks... this will not do.

- What is the issue here? why is snap4ard not connecting to the ard board thorugh the UUI? (nothing happens when I click the connect button)

- Where are the help pages for the snap4ard connectivity problems?

**Comment by Calkin-eC2L** [comment]
Also the connection to the snap4ard cloud through the UUI is not working. I get the following error:

![image](https://user-images.githubusercontent.com/35801506/37651560-2d7ede82-2c41-11e8-9d5e-a64c87c21650.png)

**Comment by afsheenam** [comment]
"Where are the help pages for the snap4ard connectivity problems?"
I will update the contents of the Troubleshooting page with the content that we had for it before. There are some lines regarding Snap4Ard there.

**Comment by ToonTalk** [comment]
Talking to Arduinos from the UUI version it will only work if you drag and drop the crx folder to chrome://extensions. You can get the folder from https://ecraft2learn.github.io/uui/snap4arduino/crx.zip -- if it works at the snap4arduino.rocks website then you have the wrong version of the extension.

The Snap4arduino help panel (from the ? button) explains about this.

**Comment by afsheenam** [comment]
I will also add it to troubleshooting guide.

Afshin

**Comment by Calkin-eC2L** [comment]
The help is all over the place now.

What exactly we get from the minuscule '?' button is very unclear at the moment. The icon should show what the program is for. In case of problems, the troubleshooting pages should be available.


Take for instance the Cura icon - when it is pressed a new window opens saying that we don't support it. This explanation should be given inside the UUI, using the entire icon as a button. What would be the function of the '?' then ? to define what Cura is for.


Comments?


Calkin Suero Montero
eCraft2Learn
Senior Researcher | Coordinator
School of Computing
University of Eastern Finland
+358 50 442 3789
________________________________

**Comment by afsheenam** [comment]
The Cura issue is now fixed. Both the help and the main tile show the same dialog inside UUI.

**Comment by Calkin-eC2L** [comment]
This is what I see on the troubleshooting page

![image](https://user-images.githubusercontent.com/35801506/37715907-e0afed18-2d25-11e8-87d3-632cd7b76027.png)

The css styling is not kicking in?

**Comment by afsheenam** [comment]
I open a new issue for this as it is confusing to have it here with the discussion about Snap4Arduino.

**Comment by Calkin-eC2L** [comment]
this relates directly to the previous comments made by you Afshin, as these are the help pages of snap4ard
