### ISSUE TITLE
Search button on eCraft Search Tool

### ISSUE THREAD

**Issue by afsheenam** [ecraft2learn/uui#23]
Search button should be removed and the "type keyword(s) here" interface should appear automatically upon load.

**Comment by phlindstedt** [comment]
I have a fix for this. Its in my fork where i'm updating to v4. You type and press enter or the search button and it will do the same work. In both mine and live version it get a lot of errors when searching.

![esearch](https://user-images.githubusercontent.com/38065886/42379239-5c218c4c-812a-11e8-966a-40d60c4093bc.PNG)

**Comment by phlindstedt** [comment]
Fixed
