### ISSUE TITLE
help for 3D slicing just launches the program

### ISSUE THREAD

**Issue by ToonTalk** [ecraft2learn/uui#37]
Instead of providing some help.

**Comment by ToonTalk** [comment]
Also only this tool is missing the feedback icon.

**Comment by afsheenam** [comment]
It does not have a feedback icon because we do not have a tool ID for it in DB. We are not sure if we keep this so I am not sure if I should add it.

**Comment by afsheenam** [comment]
The feedback button and text for about button are added.
