### ISSUE TITLE
OERs - UUI integration 

### ISSUE THREAD

**Issue by Calkin-eC2L** [ecraft2learn/uui#4]
An idea:

![image](https://user-images.githubusercontent.com/35801506/35564269-4ac99464-05c2-11e8-8864-ce02a1c2150c.png)

comments are welcome :)

**Comment by ToonTalk** [comment]
A ribbon of help buttons looks like a good idea to me.

Note that tool specific help is already available via the ? button on each tool icon. But maybe it is OK to have two ways to access the same help. And of course help that isn't tied to a specific tool needs an interface such as you suggest.

By the way the first attempt at OER integration can be seen at https://ecraft2learn.github.io/uui/index.html?&beta but Afshin plans to make it have a much better look and feel.

**Comment by Calkin-eC2L** [comment]
That is a good attempt. 
Notice thought that by having a block as a help may be confusing as the tools for the pedagogical steps are also blocks. 

If the 'How to use' for each one of the tools is already given through the '?' icon of the tool then it doesn't need to be integrated in the ribbon. Help that is related to the Electronics components (for each level: novice, intermediate, advanced, customized according to the learning analytics engine), 3D printing tutorial, S4A tutorials, Pedagogical tutorials (e.g., on the activities that can be carried out in each stage), should be in the ribbon, alongside a good, easy to understand troubleshooting (something that doesn't scare the teachers or the students).

So, let us try with the expandable ribbon idea (the ribbon can be made visible/invisible by clicking on the "Educational resources | Tutorials | FAQ") and get feedback from the teachers/students once it is implemented (in the end they suggested a ribbon in this fashion during the workshop).

Afshin, can you try implementing the integration of the OERs in this way?

**Comment by ToonTalk** [comment]
I agree. By the way the "3D printing tutorial" are really Cura tutorials and hence are available on the ? with the Cura icon. Or are we considering other ways of 3D printing?

**Comment by afsheenam** [comment]
Can I implement it this way? Yes.
But I am not a fan of integrating it as a ribbon. The UUI is based on Metro design, and what I was thinking originally about it is that it mimic Windows Start Page, so for the students it looks like they are using another Windows device. A ribbon will make it look more like a Website.
In order to keep the Windows Start Page idea and not have the Help as tiles (which I have nothing against that), I suggest something like a Windows Sidebar or Programs menu:

![image](https://user-images.githubusercontent.com/31007804/35632360-c2cdc4be-06a6-11e8-9d65-103fdbad5732.png)

This way it is still expandable/hidable, but stays inline with Windows styling.

**Comment by Calkin-eC2L** [comment]
Afshin,
that windows style (sidebar/program menu) is like a type of ribbon, just wider and taller :)
If it expands/contracts in that way after clicking on the "Educational resources | Tutorials | FAQ" title/icon (if letters can be icons) then that should do the work.

**Comment by afsheenam** [comment]
OK. I see. I have another question now, the "Educational resources | Tutorials | FAQ" link always opens the same list or each of the items in it (Educational resources, tutorials, faq) open a separate list?
If it is all in one then I can replace it with a small button with a question mark icon. If they are separate then I will need to take another approach.

**Comment by Calkin-eC2L** [comment]
"Educational resources | Tutorials | FAQ" should open the same list of resources, they are not individual items but a single block of words. A small question mark isn't optimal - spelling out what you will get if you click in that area is more informative.

**Comment by afsheenam** [comment]
This is done now.

**Comment by ToonTalk** [comment]
I think it should be

Educational resources & Tutorials & FAQ

not

Educational resources | Tutorials | FAQ

To me the use of | means I can choose one of these 3 items.

**Comment by afsheenam** [comment]
It is simple Educational Resources now. Other texts are too long. Can we agree to close this issue?

**Comment by ToonTalk** [comment]
Let's have a discussion about this. Clicking it includes many things aren't educational resources: communities, troubleshooting, teacher uploads (in some cases). How about "Help"?
