### ISSUE TITLE
Exception from Share My Work

### ISSUE THREAD

**Issue by ToonTalk** [ecraft2learn/uui#51]
Perhaps due to the fact that the tool used was None (or that the project was None).

Uncaught TypeError: Cannot read property 'ID' of undefined
    at Object.success (api-calls.js:134)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at A (jquery.js:4)
    at XMLHttpRequest.<anonymous> (jquery.js:4)
    at Object.send (jquery.js:4)
    at Function.ajax (jquery.js:4)
    at shareLocalFile (api-calls.js:123)
    at HTMLButtonElement.<anonymous> (sharing-form.js:55)

**Comment by ToonTalk** [comment]
Worked fine after I created a project and selected that instead of None.

**Comment by phlindstedt** [comment]
When None is selected, it should use -userId (negative user ID)

**Comment by afsheenam** [comment]
@LNU: Can you apply Philip's comment above to Sharing tool's code?

**Comment by bilyvka** [comment]
If i will put userId -1 this file will never be seen by others and not by the user that shared the file.
This is what we want? 
Or we want to have projectID =-1 and toolId= -1 when user share local file without project and tool? then in the sharing table it will be Project name: None, toolt name: noon.
How should it be?

**Comment by bilyvka** [comment]
Did it, will push to the master soon

**Comment by ToonTalk** [comment]
It is working well now. Only very minor remaining issue is that in

![image](https://user-images.githubusercontent.com/2138696/50083812-3fc4fb00-01f5-11e9-8315-ecf54314a212.png)

the new item doesn't have an icon in the table as the earlier two items do

**Comment by bilyvka** [comment]
Yes, I choose "white" recrangle.png file as tool icon, should I use other?
any suggestions?
Thank you
Best,
Alisa

**Comment by bilyvka** [comment]
I mean when file shared without toolid then there is no tool icon, or was it other case, problem?

**Comment by ToonTalk** [comment]
But before it was defaulting to the eCraft2Learn logo instead of a white rectangle. I think that's better but don't feel strongly about this but it should be consistent.

**Comment by bilyvka** [comment]
Sorry, i forgot about it, i will put default one, thank you

**Comment by bilyvka** [comment]
Default image is fixed

**Comment by afsheenam** [comment]
@bilyvka I am a little bit confused. In your email you mentioned setting userid to -1 but Philip's comment says negative of the userid. Which one have you applied? It seems to work now, that is why I am asking.

**Comment by bilyvka** [comment]
Hi Afsheen,

I understood negative userId its -1. So, I did userId -> -1. Otherwise, what means negative userId?

**Comment by bilyvka** [comment]
Aha, sorry, so stupid, he meant -userId, should I change to -userId instead of -1?

**Comment by afsheenam** [comment]
I think it is best if we do that. @phlindstedt any comments?

**Comment by phlindstedt** [comment]
Believe it's better to use -userid instead of -1 to keep it to same information for all shares, since all shares have a project ID and the default project "none" uses -userid as project ID.

**Comment by afsheenam** [comment]
It is settled then @bilyvka please make the change.

**Comment by bilyvka** [comment]
Did it
