### ISSUE TITLE
Confusing menu inside of Share My Work

### ISSUE THREAD

**Issue by ToonTalk** [ecraft2learn/uui#52]
For tool used there was "None" and "General" but many things shared may have been created with a text editor or camera or ... I didn't see an "Other" choice.

**Comment by afsheenam** [comment]
Any other tool can be marked as None. @bilyvka and @phlindstedt  is there a difference between None and General?

**Comment by ToonTalk** [comment]
These are odd labels for files created by tools other than those listed.

**Comment by bilyvka** [comment]
None means file created without using any tool and General with using other
tool that mentioned in the list

**Comment by heijler** [comment]
As far as I understand: 

"None" was added to the menu to address the issue that a user might upload a file that wasn't created with the UUI tools.

"General" is a tool listed in the database, this wasn't added by us, we just display all the tools listed in database + "None"


I suggest that we rename "None" to "Other". As for the "General" tool, is this actually used by any tools in the UUI?

Any input is appreciated!

**Comment by afsheenam** [comment]
@phlindstedt Correct me if I am wrong, but we use the "General" in DB to refer to any tool which is not a UUI tool. Therefore, "None" can be removed.

**Comment by phlindstedt** [comment]
In the DB it's General yes.

**Comment by afsheenam** [comment]
@heijler @bilyvka So I guess we can remove the "None" option and keep "General" as they serve the same purpose. We can decide if we want to rename the "General" to "Other" or no.

**Comment by bilyvka** [comment]
Good, None is removed from the list
