### ISSUE TITLE
Should we add BlocksCAD to the create stage?

### ISSUE THREAD

**Issue by ToonTalk** [ecraft2learn/uui#6]
https://www.blockscad3d.com/editor/ can be used without registering. A very different computation model than BeetleBlocks even though both use programs to create 3D models. It is HTTPS and loads OK in a UUI panel. Perhaps as a small icon.

**Comment by Calkin-eC2L** [comment]
For some reason my comment (from last week!) did not register :/
How many of these tools do we already have in the UUI?

**Comment by ToonTalk** [comment]
For 3D design we have Tinkercad and BeetleBlocks. And soon to add 3D Slash.

**Comment by Calkin-eC2L** [comment]
ok 3 should be plenty to choose from

**Comment by afsheenam** [comment]
I get Calkin's previous message as a No to adding more 3D tools. If there is no objection in the next 24 hours, I will close this issue.

**Comment by ToonTalk** [comment]
I agree. Also I strongly prefer the turtle-oriented BeetleBlocks to this Cartesian system.
