### ISSUE TITLE
eCraft TODO errors in console

### ISSUE THREAD

**Issue by ToonTalk** [ecraft2learn/uui#63]
It seemed to work OK but the console had

todo.js:245 Uncaught TypeError: Cannot read property 'length' of undefined
    at todo.js:245
    at todo.js:277
(anonymous) @ todo.js:245
(anonymous) @ todo.js:277
jquery.ui.min.js:6 GET https://ecraft2learn.github.io/uui/uef/plan/lib/jQuery/images/ui-bg_flat_75_ffffff_40x100.png 404
_create @ jquery.ui.min.js:6
(anonymous) @ jquery.ui.min.js:5
_createWidget @ jquery.ui.min.js:5
t.(anonymous function).(anonymous function) @ jquery.ui.min.js:5
(anonymous) @ jquery.ui.min.js:5
each @ jquery.min.js:4
each @ jquery.min.js:4
t.fn.(anonymous function) @ jquery.ui.min.js:5
(anonymous) @ index.html:79
jquery.min.js:6 GET https://ecraft2learn.github.io/uui/uef/plan/lib/jQuery/images/ui-bg_glass_75_e6e6e6_1x400.png 404
Wt @ jquery.min.js:6
css @ jquery.min.js:6
set @ jquery.min.js:6
style @ jquery.min.js:6
(anonymous) @ jquery.min.js:6
access @ jquery.min.js:4
x.fn.(anonymous function) @ jquery.min.js:6
_updateDatepicker @ jquery.ui.min.js:9
_showDatepicker @ jquery.ui.min.js:9
dispatch @ jquery.min.js:5
v.handle @ jquery.min.js:5
jquery.min.js:6 GET https://ecraft2learn.github.io/uui/uef/plan/lib/jQuery/images/ui-bg_glass_55_fbf9ee_1x400.png 404
Wt @ jquery.min.js:6
css @ jquery.min.js:6
set @ jquery.min.js:6
style @ jquery.min.js:6
(anonymous) @ jquery.min.js:6
access @ jquery.min.js:4
x.fn.(anonymous function) @ jquery.min.js:6
_updateDatepicker @ jquery.ui.min.js:9
_showDatepicker @ jquery.ui.min.js:9
dispatch @ jquery.min.js:5
v.handle @ jquery.min.js:5
jquery.min.js:6 GET https://ecraft2learn.github.io/uui/uef/plan/lib/jQuery/images/ui-bg_highlight-soft_75_cccccc_1x100.png 404
Wt @ jquery.min.js:6
css @ jquery.min.js:6
set @ jquery.min.js:6
style @ jquery.min.js:6
(anonymous) @ jquery.min.js:6
access @ jquery.min.js:4
x.fn.(anonymous function) @ jquery.min.js:6
_updateDatepicker @ jquery.ui.min.js:9
_showDatepicker @ jquery.ui.min.js:9
dispatch @ jquery.min.js:5
v.handle @ jquery.min.js:5
jquery.min.js:6 GET https://ecraft2learn.github.io/uui/uef/plan/lib/jQuery/images/ui-icons_222222_256x240.png 404
Wt @ jquery.min.js:6
css @ jquery.min.js:6
set @ jquery.min.js:6
style @ jquery.min.js:6
(anonymous) @ jquery.min.js:6
access @ jquery.min.js:4
x.fn.(anonymous function) @ jquery.min.js:6
_updateDatepicker @ jquery.ui.min.js:9
_showDatepicker @ jquery.ui.min.js:9
dispatch @ jquery.min.js:5
v.handle @ jquery.min.js:5
ui-bg_glass_75_dadada_1x400.png:1 GET https://ecraft2learn.github.io/uui/uef/plan/lib/jQuery/images/ui-bg_glass_75_dadada_1x400.png 404

**Comment by phlindstedt** [comment]
I also get a lot of missing images, but not the 3 first rows you have with todo.js is now fixed.

**Comment by ToonTalk** [comment]
Seems to work for me now too without the exception and only missing images.
