### ISSUE TITLE
Should we add 3D Slash to the create stage?

### ISSUE THREAD

**Issue by ToonTalk** [ecraft2learn/uui#7]
https://www.3dslash.net/slash.php loads fine in a panel in the UUI. It is simpler (and more fun) than TinkerCad but not as expressive. Small icon?

**Comment by Calkin-eC2L** [comment]
looks nice :) I would say small icon. Do we get any knowledge/input for the learning analytics from this?

**Comment by ToonTalk** [comment]
Students can upload the STL file they created for learning analytics. Maybe Ilka or Tapani know if more can be done.

**Comment by ToonTalk** [comment]
3D Slash now added as a small icon
