### ISSUE TITLE
Share my work -download does not work

### ISSUE THREAD

**Issue by ReneAlimisi** [ecraft2learn/uui#72]
I was testing the "'share my work'' tool
I created several works and I uploaded files locally from my computer.
Question 1:
What if a project/work required the use of more than one tool. From the list you can only select one.
Question 2:
When I m selecting download...nothing happens.

<img width="960" alt="download-sharework" src="https://user-images.githubusercontent.com/46059341/50368069-d0049680-058d-11e9-8b12-c306198e8db3.png">

**Comment by Calkin-eC2L** [comment]
I think that you could download only after the authorisation has been granted (in the status bar)... (?)

**Comment by Calkin-eC2L** [comment]
how is the authorisation given? I can not find this in the learning analytics

**Comment by bilyvka** [comment]
Fixed
