### ISSUE TITLE
eCraft Plan - mobile use

### ISSUE THREAD

**Issue by MareenaUEF** [ecraft2learn/uui#75]
Issue 1: The TEXT tool does not work with a device that doesn't have external keyboard because the keyboard does not open to my screen. So, I can't type anything on the "canvas".

Issue 2: The picture I upload does not load nicely on the "canvas".

These detected by using iPhone 5s

**Comment by phlindstedt** [comment]
Issue 1: should be fixed now.

Issue 2: I can't seems to find why it rotate the image when adding it on mobile only. (at least thats the problem on my phone). Any ideas @afsheenam ?
