### ISSUE TITLE
The tool help-windows - mobile use

### ISSUE THREAD

**Issue by MareenaUEF** [ecraft2learn/uui#76]
Issue: In all the tools (when question mark pressed) the help windows open but you cannot see all the text because that window doesn't scroll with you. Only the UUI page behind that window is scrolling.

**Comment by phlindstedt** [comment]
What browser are you using on your phone? And could you include a screen shot?

Looks fine on my phone using Chrome

**Comment by afsheenam** [comment]
Works fine on my Mobile with Chrome as well. From the start of the project it was decided that we only support Chrome.
