### ISSUE TITLE
eCraft search output

### ISSUE THREAD

**Issue by Calkin-eC2L** [ecraft2learn/uui#79]
eCraft search: check output for 'porn' and 'sex' - it may be problematic...

![image](https://user-images.githubusercontent.com/35801506/50476776-19137b00-09d2-11e9-9efc-86850ddbd585.png)

**Comment by afsheenam** [comment]
I have discussed this with Tapani. The filter is there and is working and that is why there are no images in the results with pornographic content. Do you want no result at all?

**Comment by afsheenam** [comment]
Based on the emails between Baran, Me, Tapani, I am closing this. From Tapani's email:

"Now the search tool has a profanity filter. There are more than 3000 profanity keywords that are being checked before the search is triggered."
