### ISSUE TITLE
Trouble with troubleshooting

### ISSUE THREAD

**Issue by ToonTalk** [ecraft2learn/uui#8]
Clicking on troubleshooting the UUI leads to 404. The file help\troubleshooting\index.html should be linked or moved and its style updated.

Clicking on troubleshooting 3D Printing results in 

ultimaker.component-library.js:6 Uncaught DOMException: Blocked a frame with origin "https://ultimaker.com" from accessing a cross-origin frame.
    at e.value (https://d3v5bfco3dani2.cloudfront.net/build/main.bundle.3fcf86fa280180aec92f.js:13:5638)
    at e.u (https://d3v5bfco3dani2.cloudfront.net/build/main.bundle.3fcf86fa280180aec92f.js:12:27171)
    at HTMLDocument.<anonymous> (https://d3v5bfco3dani2.cloudfront.net/build/main.bundle.3fcf86fa280180aec92f.js:13:5002)

**Comment by afsheenam** [comment]
All of these are fixed now. The only problem is with the styling of the AI Teacher Guide. I will update the style with the oer-style file that we use for all of the OER pages.

**Comment by ToonTalk** [comment]
The AI Guides (the student version is almost ready) are on ecraft2learngithub.io/ai/AI-Teacher-Guide (probably should have been called  just guide) are  in the ai project not the uui. This is because they rely upon lots of Snap! project files and much more.  I have added OER CSS to the latest version. I suggest that their URLs from the UUI be 

/ai//AI-Teacher-Guide/chapter-1.html#teacher
/ai//AI-Teacher-Guide/chapter-1.html#student
etc.

Note that this will work for both ecraft2learngithub.io and localhost (if set up right).

**Comment by ToonTalk** [comment]
Links to all the chapters (and more) is at
ecraft2learn.github.io/ai/

**Comment by afsheenam** [comment]
I see that the guides are available through the OER panel and AI section. Should I mark this as done then?
Also, I find it a little bit weird that the teacher guides are available through UUI. To me, the UUI is the student side of things, should a student have access to a guide which is aimed at the teacher?

**Comment by ToonTalk** [comment]
Maybe but I lean towards openness - let students read what they want (so long as there aren't any "spoilers" in teacher materials that might ruin an exercise or quiz).
