### ISSUE TITLE
Self-reflection module

### ISSUE THREAD

**Issue by Calkin-eC2L** [ecraft2learn/uui#84]
the self-reflection space does not work - no input is possible to be added to the small window that shows up.
![image](https://user-images.githubusercontent.com/35801506/50529128-73f4c180-0afb-11e9-9a66-85ee16e96c45.png)

**Comment by bilyvka** [comment]
Explanation: Reflection module requests questions from Tapani's API (https://cs.uef.fi/~tapanit/ecraft2learn/api/pilot_2/get_reflection_pilot_2.php ) that should return a question for a specific sessionId. For the moment API returns only one questions for sessionid 11. That is why the reflection window is empty.

**Comment by Calkin-eC2L** [comment]
How can this be solved? This should have been corrected last month

**Comment by bilyvka** [comment]
Well, self evaluation module was implemented in June 2018.

**Comment by bilyvka** [comment]
@Tapani How it can be solved?

**Comment by Calkin-eC2L** [comment]
yes, but it is not working properly now 2 days before the final deadline

**Comment by Calkin-eC2L** [comment]
Tapani is trying to fix another module at the moment - it will take some time for him to reply

**Comment by Calkin-eC2L** [comment]
the self-reflection window appears now and I can write on it. The widow has a weird 'Hihi' title on it. The title should be 'Self-reflection space' or something similar

![image](https://user-images.githubusercontent.com/35801506/50537852-4563fe80-0b6e-11e9-9b84-1b8196af37c0.png)

**Comment by tapanit-e** [comment]
It is a message from a teacher...

Terveisin,
Tapani Toivonen

**Comment by Calkin-eC2L** [comment]
I sent the self-reflection request through the Call4Action module and I did not write Hihi in it....
did someone else sent this request?

**Comment by Calkin-eC2L** [comment]
the same window pops up and the same weird 'Hihi' is there. LNU fix this. @bilyvka 


![image](https://user-images.githubusercontent.com/35801506/50537974-557cdd80-0b70-11e9-8b4c-93661d1cbe14.png)

**Comment by heijler** [comment]
Agreed that it shouldn't display "Hihi!", but rather an actual question or message from the teacher. However, this isn't something LNU can fix since the question/message (in this case "Hihi!") of the reflection window is received from a UEF server that we have no access to. @Tapani any input?

**Comment by tapanit-e** [comment]
It should say Hihi because that is the text that the teacher wrote to the students.

**Comment by Calkin-eC2L** [comment]
**the thing is that I wrote the text in the LA system**. 
What I wrote is displayed in the _Action List blue box_. **I did not write 'Hihi' any where in the LA system when requesting the student to self-reflect**. Where is this Hihi coming from??
@ToonTalk @bilyvka @heijler

**Comment by afsheenam** [comment]
I used the same interface mentioned by Tapani to change the message.
