### ISSUE TITLE
eCraft Plan should be eCraft Sket

### ISSUE THREAD

**Issue by Calkin-eC2L** [ecraft2learn/uui#85]
the name of the tool should be updated I think. Please double check how this has been described in D4.4 for instance

**Comment by afsheenam** [comment]
In latest version of D4.4 it is called eCraft Plan, I can change the name here, I will wait for confirmation that the name has been changed in the document an then do it.

**Comment by Calkin-eC2L** [comment]
Ken, how have we called this tool previously in other deliverables? @ToonTalk

**Comment by afsheenam** [comment]
At least I know in D4.3 it is calle eCraft Plan

**Comment by Calkin-eC2L** [comment]
If that is the case and it has been called eCraft Plan in other documents then we leave it as it is... it is confusing with the functionality of eCraft TODO though.

**Comment by afsheenam** [comment]
Then I close this issue an we make no changes.
