### ISSUE TITLE
About help pages links to about help pages don't work

### ISSUE THREAD

**Issue by ToonTalk** [ecraft2learn/uui#9]
For example the help page for TinkerCad 3D Design links to beetleblocks-help.html but when displayed in a panel it results in /uui/beetleblocks-help.html not found. It should be looking for /uui/about/beetleblocks-help.html

**Comment by afsheenam** [comment]
Do you mean the help pages that are activated by the little question mark on the tiles? Because I just tested it and it works.

**Comment by ToonTalk** [comment]
Try this:

Click on the TinkerCad ? and then click on the BeetleBlocks link on that page. I get 404 for https://ecraft2learn.github.io/uui/beetleblocks-help.html

**Comment by afsheenam** [comment]
This is fixed now. I am not closing it and will wait for more tests from you.

**Comment by ToonTalk** [comment]
Ardublock and Netsblox help pages have broken links to Snap and Snap4Arduino.

Arduino (web) help page has broken link to Ardublock.

Everything else checks out fine.
